### ISSUE TITLE
Removing Inactive Maintainers

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/community#817]
There are a number of maintainers listed in teams.yaml who appear to be no longer active in the project.  I am tagging each of you here to give you the opportunity to clarify if you still intend to be active in the project (or in case you were included in error).  I will open a PR to remove these maintainers, and move them to emeritus status on eng.istio.io unless I hear otherwise on October 10.

@adammil2000, @andraxylia, @brian-avery, @clyang82, @elfinhe, @fleeto, @gbaufake, @jasonwzm, @john-a-joyce, @liamawhite, @loverto, @Nino-K, @rcaballeromx, @rlenglet, @rshriram, @SataQiu, @tiswanso, @venilnoronha, @yxue

**Comment by ericvn** [comment]
A couple of additional comments and @therealmitchconnors can correct if needed.

https://github.com/istio/community/blob/master/ROLES.md?plain=1#L234-L236 is the section of the community docs that discuss this. 

The `extended period of time` is not defined, but for this issue is 1 yr. Note that the inactive tab on the dashboard is 90 days for maintainers. If you make a contribution, the clock starts over. I think just replying to this issue would be enough.

**Comment by john-a-joyce** [comment]
Cisco has just asked me to again become active in the project so please don't remove me

**Comment by Nino-K** [comment]
I would like to stay as an active member, thanks.

**Comment by brian-avery** [comment]
I'm no longer able to take an active role. Thanks for everything guys! Please feel free to move me to emeritus status.
