### ISSUE TITLE
Slack invite link is broken

### ISSUE THREAD

**Issue by ksudate** [istio/community#885]
Slack invite link is broken.
https://istio.io/latest/get-involved/
The following PR indicates that the service needs to be updated.
https://github.com/istio/istio.io/issues/10865

Need to create a new link and update it.
https://docs.google.com/document/d/1Pf6vS5SiYuSD55atbosoSHktIi1N08p-P480buzCrDk/edit#

**Comment by ericvn** [comment]
Transferring this to istio/community for fixing.

**Comment by sybadm** [comment]
I never seen the slack invite working. Does it really allow people to join? 

Such a good technology but it seems everyone is busy in making things in closed walls. I am very new to Istio and but not new to the  kubernets and containerisation. I felt it very hard to interact within Istio community. There are stackoverflow or Istio own forums where more than 70% threads are not answered. This doesn’t reflect good to me; no doubt you have good product but if you fail to build user base then I’m sorry you don’t have great future and people will turn somewhere else. Be serious about the users and their queries as you are on developing the technology for next generation.

**Comment by howardjohn** [comment]
Can you try it now

**Comment by craigbox** [comment]
Hi @ksudate and @sybadm: I'm sorry for the delay in getting this fixed.  We're in "flux" at the moment as we move from Google infrastructure to CNCF infrastructure.  When I worked at Google I would have fixed this immediately :)

The Slack thing we run is a workaround because their software isn't made for communities like this, but it's the software that everyone in the CNCF seems to use. There's no way to issue invites from Slack itself, so we have to generate these tokens which are valid for a few hundred users.  When those are all used up, we have to generate a new URL.

It's definitely working now!

As for questions and answers on Stack Overflow and Discuss, I do also see there's a lot of questions not being answered. That's a challenge when there are so many vendors.  One thing that we're going to try and do in the Steering committee this term is encourage our community to help answer user questions.   Developers are busy developing and don't tend to pay as much attention as they do early in the life of a project.

(@howardjohn is excluded from this critique, as not only has he replied on this thread, but also replies to many Slack threads)

**Comment by sybadm** [comment]
Awesome! Thanks for the quick response. This is how it should be. I’m very happy to support the community wherever I can.

tx

**Comment by ericvn** [comment]
Thanks for the report. This should be working again. If this is still failing, please reopen the issue.
